name: Node CI

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # uploade build artifact 
    - uses: actions/upload-artifact@v3
      with:
        name: webpack artifacts
        path: public/
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@v3
        with:
          name: webpack artifacts
          path: public/
      - name: npm install and test
        run: |
          npm install
          npm test -- -u
        env:
          CI: true
          
  Build-Docker-Github:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, Push
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download built artifact
      uses: actions/download-artifact@main
      with:
        name: webpack artifacts
        path: public
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
        repository: aaronk1998/devops-p8/tic-tac-toe
        tag_with_sha: true

